services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime  # Chỉ build stage runtime
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
