export const trainingStages = [
  {
    id: 'giai-doan-1',
    name: 'Giai đoạn Đệ Tử',
    duration: '1 năm',
    targetGroup: 'Các em tốt nghiệp PTTH, Cao Đẳng hoặc Đại học',
    purpose: [
      'Chúa gọi trực tiếp hay thông qua một ai đó',
      'Ứng sinh có “Thích” và “Hợp” để sống ơn gọi',
      'Muốn đi theo Chúa',
      'Được Chúa biến đổi và sống hòa đồng trong đời tu',
      'Chu toàn bổn phận thiêng liêng và tự nhiên một cách kiên trì.',
      'Chuẩn bị cho ứng sính vào Thỉnh Sinh bằng cách cho tham gia đầy đủ đời sống cầu nguyện và sinh hoạt cộng đoàn, trong giới hạn một Để Tử.',
    ],
    trainingProgram: [
      'Tiếng Anh',
      'Nhân bản',
      'Tri thức',
      'Giáo lý',
      'Tông đồ',
      'Đức tin',
      'Học về Tiểu sử Đấng Sáng lập',
    ],
  },
  {
    id: 'giai-doan-2',
    name: 'Giai đoạn Thỉnh Sinh',
    duration: '2 năm',
    targetGroup: 'Các em Qua Giai Đoạn Đệ Tử',
    purpose: [
      'Giúp ứng sinh nhận biết ơn gọi của mình và của Hội Dòng',
      'Giúp Hội Dòng tìm hiểu tính tình, khả năng và lý do chọn lựa đời sống tu trì của ứng sinh',
      'Chuẩn bị cho ứng sinh vào Tập Viện bằng cách cho tham gia đầy đủ đời sống cầu nguyện và sinh hoạt cộng đoàn, trong giới hạn một Thỉnh Sinh.',
    ],
    trainingProgram: [
      'Nhân bản trong đời tu',
      'Tập sống quân bình tâm lý',
      'Cầu nguyện',
      'Nguyện ngắm',
    ],
  },
  {
    id: 'giai-doan-3',
    name: 'Giai đoạn TẬP VIỆN',
    duration: '2 năm',
    purpose: [
      'Giúp ứng sinh nhận biết chắc chắn và rõ ràng hơn ơn gọi của mình và của Dòng Anh Em Đức Maria',
      'Thực nghiệm lối sống của Hội Dòng',
      'Uốn nắn trí tuệ và trái tim theo tinh thần của Hội Dòng',
      'Hội Dòng kiểm chứng ý định và tư cách thích đáng của ứng sinh đối với đời sống tu trì trong Hội Dòng',
    ],
    trainingProgram: [
      'Vun trồng các đức tin nhân bản và Kitô giáo',
      'Học tập nguyện ngắm và từ bỏ mình như là những phương thế hữu hiệu nhất để đạt tới sự hoàn thiện',
      'Đọc và suy niệm Kinh Thánh để chiêm ngưỡng mầu nhiệm cứu độ',
      'Học phụng vụ để tôn thờ Thiên Chúa cách xứng hợp',
      'Tập sống đời thánh hiến cho Thiên Chúa và tha nhân trong Đức Kitô bằng các lời khuyên Phúc Âm',
      'Nắm vững đặc tính, tinh thần, mục đích, kỷ luật, lịch sử và đời sống của Hội Dòng',
      'Thấm nhuần tinh thần yêu mến Giáo hội và các vị chủ chăn',
    ],
  },
  {
    id: 'giai-doan-4',
    name: 'Giai đoạn HỌC VIỆN',
    duration: '6 năm',
    purpose: [
      'Giúp kiện toàn việc huấn luyện các Sư Huynh khấn tạm',
      'Hướng dẫn chị em đến sự dâng hiến trọn vẹn và dứt khoát cho Chúa Kitô trong đời sống đặc thù của Hội Dòng',
      'Trau dồi cho chị em có khả năng chu toàn sứ mạng của Dòng Anh Em Đức Maria cách thích đáng hơn',
      'Giúp chị em hòa hợp các yếu tố của chương trình huấn luyện sao cho có được một đời sống thuần nhất',
    ],
    trainingProgram: [
      'Đào sâu linh đạo của Cha Thánh Marcelline Champagnat và Dòng Anh Em Đức Maria',
      'Đào sâu mầu nhiệm Chúa Kitô, mầu nhiệm Thiên Chúa Ba Ngôi và mầu nhiệm Giáo Hội',
      'Học Kinh Thánh, đặc biệt Thánh vịnh, Phúc âm và các thư của Thánh Phaolô',
      'Học lịch sử Giáo hội Công Giáo',
      'Học sư phạm giáo lý',
      'Huấn luyện về khả năng chuyên môn, học nghề hoặc bổ túc nghiệp vụ để nâng cao hiệu năng các công việc do Hội Dòng và cộng đoàn giao phó',
    ],
  },
];
